import './globals.css'
import {Inter} from 'next/font/google'
import React from "react";
import {AuthProvider} from "@/lib/providers/auth-provider";
import {ShopProvider} from "@/lib/providers/shop-provider";
import Header from "@/components/layout/Header";
import {CartProvider} from "@/lib/providers/cart-provider";
import Footer from "@/components/layout/Footer";
import BottomNavigationMobile from "@/components/layout/BottomNavigationMobile";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AuthProvider>
            <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
            />
            <ShopProvider code={'OngButShop'}>
                <CartProvider>
                    <Header/>
                    {children}
                    <Footer />
                    <BottomNavigationMobile />
                </CartProvider>
            </ShopProvider>
            <ToastContainer />
        </AuthProvider></body>
        </html>
    )
}
